// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:nba_api/domain/players/models/player_detail.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'player.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'player.g.dart';

@freezed
class Players with _$Players {
  const factory Players({
    @JsonKey(name: 'data') @Default([]) List<PlayerDetail> player,
    Map<String, dynamic>? meta,
  }) = _Players;

  factory Players.fromJson(Map<String, Object?> json) =>
      _$PlayersFromJson(json);
}
