// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'team.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'team.g.dart';

@freezed
class Team with _$Team {
  const factory Team({
    @Default(0) int id,
    @Default('') String abbreviation,
    @Default('') String city,
    @Default('') String conference,
    @Default('') String division,
    @JsonKey(name: 'full_name') @Default('') String fullName,
    @Default('') String name,
  }) = _Team;

  factory Team.fromJson(Map<String, Object?> json) => _$TeamFromJson(json);
}
